using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace NesEmu.CPU {
    public static class OpCodeList {
        public static readonly OpCode[] OpCodes = new OpCode[] {
            new OpCode(0x00, Op.BRK, 1, 7, AddressingMode.NoneAddressing),
            new OpCode(0x01, Op.ORA, 2, 6, AddressingMode.IndirectX),
            new OpCode(0x02, Op.KIL, 1, 0,  AddressingMode.NoneAddressing),
            new OpCode(0x03, Op._SLO, 2, 8,  AddressingMode.IndirectX),
            new OpCode(0x04, Op._NOP, 2, 3,  AddressingMode.ZeroPage),
            new OpCode(0x05, Op.ORA, 2, 3, AddressingMode.ZeroPage),
            new OpCode(0x06, Op.ASL, 2, 5, AddressingMode.ZeroPage),
            new OpCode(0x07, Op._SLO, 2, 5,  AddressingMode.ZeroPage),
            new OpCode(0x08, Op.PHP, 1, 3, AddressingMode.NoneAddressing),
            new OpCode(0x09, Op.ORA, 2, 2, AddressingMode.Immediate),
            new OpCode(0x0a, Op.ASL_ACC, 1, 2, AddressingMode.Accumulator),
            new OpCode(0x0b, Op.AAC, 2, 2,  AddressingMode.Immediate),
            new OpCode(0x0c, Op._NOP, 3, 4,  AddressingMode.Absolute),
            new OpCode(0x0d, Op.ORA, 3, 4, AddressingMode.Absolute),
            new OpCode(0x0e, Op.ASL, 3, 6, AddressingMode.Absolute),
            new OpCode(0x0f, Op._SLO, 3, 6,  AddressingMode.Absolute),
            new OpCode(0x10, Op.BPL, 2, 2 /*(+1 if branch succeeds +2 if to a new page)*/, AddressingMode.Relative),
            new OpCode(0x11, Op.ORA, 2, 5 /*+1 if page crossed*/, AddressingMode.IndirectY),
            new OpCode(0x12, Op.KIL, 1, 0,  AddressingMode.NoneAddressing),
            new OpCode(0x13, Op._SLO, 2, 8,  AddressingMode.IndirectY),
            new OpCode(0x14, Op._NOP, 2, 4,  AddressingMode.ZeroPageX),
            new OpCode(0x15, Op.ORA, 2, 4, AddressingMode.ZeroPageX),
            new OpCode(0x16, Op.ASL, 2, 6, AddressingMode.ZeroPageX),
            new OpCode(0x17, Op._SLO, 2, 6,  AddressingMode.ZeroPageX),
            new OpCode(0x18, Op.CLC, 1, 2, AddressingMode.NoneAddressing),
            new OpCode(0x19, Op.ORA, 3, 4 /*+1 if page crossed*/, AddressingMode.AbsoluteY),
            new OpCode(0x1A, Op._NOP, 1, 2,  AddressingMode.NoneAddressing),
            new OpCode(0x1b, Op._SLO, 3, 7,  AddressingMode.AbsoluteY),
            new OpCode(0x1c, Op._NOP, 3, 4,  AddressingMode.AbsoluteX),
            new OpCode(0x1d, Op.ORA, 3, 4 /*+1 if page crossed*/, AddressingMode.AbsoluteX),
            new OpCode(0x1e, Op.ASL, 3, 7, AddressingMode.AbsoluteX),
            new OpCode(0x1f, Op._SLO, 3, 7,  AddressingMode.AbsoluteX),
            new OpCode(0x20, Op.JSR, 3, 6, AddressingMode.Absolute),
            new OpCode(0x21, Op.AND, 2, 6, AddressingMode.IndirectX),
            new OpCode(0x22, Op.KIL, 1, 0,  AddressingMode.NoneAddressing),
            new OpCode(0x23, Op._RLA, 2, 8,  AddressingMode.IndirectX),
            new OpCode(0x24, Op.BIT, 2, 3, AddressingMode.ZeroPage),
            new OpCode(0x25, Op.AND, 2, 3, AddressingMode.ZeroPage),
            new OpCode(0x26, Op.ROL, 2, 5, AddressingMode.ZeroPage),
            new OpCode(0x27, Op._RLA, 2, 5,  AddressingMode.ZeroPage),
            new OpCode(0x28, Op.PLP, 1, 4, AddressingMode.NoneAddressing),
            new OpCode(0x29, Op.AND, 2, 2, AddressingMode.Immediate),
            new OpCode(0x2a, Op.ROL_ACC, 1, 2, AddressingMode.Accumulator),
            new OpCode(0x2b, Op.AAC, 2, 2,  AddressingMode.Immediate),
            new OpCode(0x2c, Op.BIT, 3, 4, AddressingMode.Absolute),
            new OpCode(0x2d, Op.AND, 3, 4, AddressingMode.Absolute),
            new OpCode(0x2e, Op.ROL, 3, 6, AddressingMode.Absolute),
            new OpCode(0x2f, Op._RLA, 3, 6,  AddressingMode.Absolute),
            new OpCode(0x30, Op.BMI, 2, 2 /*(+1 if branch succeeds +2 if to a new page)*/, AddressingMode.Relative),
            new OpCode(0x31, Op.AND, 2, 5 /*+1 if page crossed*/, AddressingMode.IndirectY),
            new OpCode(0x32, Op.KIL, 1, 0,  AddressingMode.NoneAddressing),
            new OpCode(0x33, Op._RLA, 2, 8,  AddressingMode.IndirectY),
            new OpCode(0x34, Op._NOP, 2, 4,  AddressingMode.ZeroPageX),
            new OpCode(0x35, Op.AND, 2, 4, AddressingMode.ZeroPageX),
            new OpCode(0x36, Op.ROL, 2, 6, AddressingMode.ZeroPageX),
            new OpCode(0x37, Op._RLA, 2, 6,  AddressingMode.ZeroPageX),
            new OpCode(0x38, Op.SEC, 1, 2, AddressingMode.NoneAddressing),
            new OpCode(0x39, Op.AND, 3, 4 /*+1 if page crossed*/, AddressingMode.AbsoluteY),
            new OpCode(0x3A, Op._NOP, 1, 2,  AddressingMode.NoneAddressing),
            new OpCode(0x3b, Op._RLA, 3, 7,  AddressingMode.AbsoluteY),
            new OpCode(0x3c, Op._NOP, 3, 4,  AddressingMode.AbsoluteX),
            new OpCode(0x3d, Op.AND, 3, 4 /*+1 if page crossed*/, AddressingMode.AbsoluteX),
            new OpCode(0x3e, Op.ROL, 3, 7, AddressingMode.AbsoluteX),
            new OpCode(0x3f, Op._RLA, 3, 7,  AddressingMode.AbsoluteX),
            new OpCode(0x40, Op.RTI, 1, 6, AddressingMode.NoneAddressing),
            new OpCode(0x41, Op.EOR, 2, 6, AddressingMode.IndirectX),
            new OpCode(0x42, Op.KIL, 1, 0,  AddressingMode.NoneAddressing),
            new OpCode(0x43, Op._SRE, 2, 8,  AddressingMode.IndirectX),
            new OpCode(0x44, Op._NOP, 2, 3,  AddressingMode.ZeroPage),
            new OpCode(0x45, Op.EOR, 2, 3, AddressingMode.ZeroPage),
            new OpCode(0x46, Op.LSR, 2, 5, AddressingMode.ZeroPage),
            new OpCode(0x47, Op._SRE, 2, 5,  AddressingMode.ZeroPage),
            new OpCode(0x48, Op.PHA, 1, 3, AddressingMode.NoneAddressing),
            new OpCode(0x49, Op.EOR, 2, 2, AddressingMode.Immediate),
            new OpCode(0x4a, Op.LSR_ACC, 1, 2, AddressingMode.Accumulator),
            new OpCode(0x4b, Op.ASR, 2, 2,  AddressingMode.Immediate),
            new OpCode(0x4c, Op.JMP, 3, 3, AddressingMode.Absolute), //AddressingMode that acts as Immidiate
            new OpCode(0x4d, Op.EOR, 3, 4, AddressingMode.Absolute),
            new OpCode(0x4e, Op.LSR, 3, 6, AddressingMode.Absolute),
            new OpCode(0x4f, Op._SRE, 3, 6,  AddressingMode.Absolute),
            new OpCode(0x50, Op.BVC, 2, 2 /*(+1 if branch succeeds +2 if to a new page)*/, AddressingMode.Relative),
            new OpCode(0x51, Op.EOR, 2, 5 /*+1 if page crossed*/, AddressingMode.IndirectY),
            new OpCode(0x52, Op.KIL, 1, 0,  AddressingMode.NoneAddressing),
            new OpCode(0x53, Op._SRE, 2, 8,  AddressingMode.IndirectY),
            new OpCode(0x54, Op._NOP, 2, 4,  AddressingMode.ZeroPageX),
            new OpCode(0x55, Op.EOR, 2, 4, AddressingMode.ZeroPageX),
            new OpCode(0x56, Op.LSR, 2, 6, AddressingMode.ZeroPageX),
            new OpCode(0x57, Op._SRE, 2, 6,  AddressingMode.ZeroPageX),
            new OpCode(0x58, Op.CLI, 1, 2, AddressingMode.NoneAddressing),
            new OpCode(0x59, Op.EOR, 3, 4 /*+1 if page crossed*/, AddressingMode.AbsoluteY),
            new OpCode(0x5A, Op._NOP, 1, 2,  AddressingMode.NoneAddressing),
            new OpCode(0x5b, Op._SRE, 3, 7,  AddressingMode.AbsoluteY),
            new OpCode(0x5c, Op._NOP, 3, 4,  AddressingMode.AbsoluteX),
            new OpCode(0x5d, Op.EOR, 3, 4 /*+1 if page crossed*/, AddressingMode.AbsoluteX),
            new OpCode(0x5e, Op.LSR, 3, 7, AddressingMode.AbsoluteX),
            new OpCode(0x5f, Op._SRE, 3, 7,  AddressingMode.AbsoluteX),
            new OpCode(0x60, Op.RTS, 1, 6, AddressingMode.NoneAddressing),
            new OpCode(0x61, Op.ADC, 2, 6, AddressingMode.IndirectX),
            new OpCode(0x62, Op.KIL, 1, 0,  AddressingMode.NoneAddressing),
            new OpCode(0x63, Op._RRA, 2, 8,  AddressingMode.IndirectX),
            new OpCode(0x64, Op._NOP, 2, 3,  AddressingMode.ZeroPage),
            new OpCode(0x65, Op.ADC, 2, 3, AddressingMode.ZeroPage),
            new OpCode(0x66, Op.ROR, 2, 5, AddressingMode.ZeroPage),
            new OpCode(0x67, Op._RRA, 2, 5,  AddressingMode.ZeroPage),
            new OpCode(0x68, Op.PLA, 1, 4, AddressingMode.NoneAddressing),
            new OpCode(0x69, Op.ADC, 2, 2, AddressingMode.Immediate),
            new OpCode(0x6a, Op.ROR_ACC, 1, 2, AddressingMode.Accumulator),
            new OpCode(0x6b, Op.ARR, 2, 2,  AddressingMode.Immediate),
            new OpCode(0x6c, Op.JMP, 3, 5, AddressingMode.Indirect), //AddressingMode:Indirect with 6502 bug
            new OpCode(0x6d, Op.ADC, 3, 4, AddressingMode.Absolute),
            new OpCode(0x6e, Op.ROR, 3, 6, AddressingMode.Absolute),
            new OpCode(0x6f, Op._RRA, 3, 6,  AddressingMode.Absolute),
            new OpCode(0x70, Op.BVS, 2, 2 /*(+1 if branch succeeds +2 if to a new page)*/, AddressingMode.Relative),
            new OpCode(0x71, Op.ADC, 2, 5 /*+1 if page crossed*/, AddressingMode.IndirectY),
            new OpCode(0x72, Op.KIL, 1, 0,  AddressingMode.NoneAddressing),
            new OpCode(0x73, Op._RRA, 2, 8,  AddressingMode.IndirectY),
            new OpCode(0x74, Op._NOP, 2, 4,  AddressingMode.ZeroPageX),
            new OpCode(0x75, Op.ADC, 2, 4, AddressingMode.ZeroPageX),
            new OpCode(0x76, Op.ROR, 2, 6, AddressingMode.ZeroPageX),
            new OpCode(0x77, Op._RRA, 2, 6,  AddressingMode.ZeroPageX),
            new OpCode(0x78, Op.SEI, 1, 2, AddressingMode.NoneAddressing),
            new OpCode(0x79, Op.ADC, 3, 4 /*+1 if page crossed*/, AddressingMode.AbsoluteY),
            new OpCode(0x7A, Op._NOP, 1, 2,  AddressingMode.NoneAddressing),
            new OpCode(0x7b, Op._RRA, 3, 7,  AddressingMode.AbsoluteY),
            new OpCode(0x7c, Op._NOP, 3, 4,  AddressingMode.AbsoluteX),
            new OpCode(0x7d, Op.ADC, 3, 4 /*+1 if page crossed*/, AddressingMode.AbsoluteX),
            new OpCode(0x7e, Op.ROR, 3, 7, AddressingMode.AbsoluteX),
            new OpCode(0x7f, Op._RRA, 3, 7,  AddressingMode.AbsoluteX),
            new OpCode(0x80, Op._NOP, 2, 2,  AddressingMode.Immediate),
            new OpCode(0x81, Op.STA, 2, 6, AddressingMode.IndirectX),
            new OpCode(0x82, Op._NOP, 2, 2,  AddressingMode.Immediate),
            new OpCode(0x83, Op._SAX, 2, 6,  AddressingMode.IndirectX),
            new OpCode(0x84, Op.STY, 2, 3, AddressingMode.ZeroPage),
            new OpCode(0x85, Op.STA, 2, 3, AddressingMode.ZeroPage),
            new OpCode(0x86, Op.STX, 2, 3, AddressingMode.ZeroPage),
            new OpCode(0x87, Op._SAX, 2, 3,  AddressingMode.ZeroPage),
            new OpCode(0x88, Op.DEY, 1, 2, AddressingMode.NoneAddressing),
            new OpCode(0x89, Op._NOP, 2, 2,  AddressingMode.Immediate),
            new OpCode(0x8a, Op.TXA, 1, 2, AddressingMode.NoneAddressing),
            // Skipping this for now since it's unstable
            new OpCode(0x8b, Op.XAA, 2, 2,  AddressingMode.Immediate),
            new OpCode(0x8c, Op.STY, 3, 4, AddressingMode.Absolute),
            new OpCode(0x8d, Op.STA, 3, 4, AddressingMode.Absolute),
            new OpCode(0x8e, Op.STX, 3, 4, AddressingMode.Absolute),
            new OpCode(0x8f, Op._SAX, 3, 4,  AddressingMode.Absolute),
            new OpCode(0x90, Op.BCC, 2, 2 /*(+1 if branch succeeds +2 if to a new page)*/, AddressingMode.Relative),
            new OpCode(0x91, Op.STA, 2, 6, AddressingMode.IndirectY),
            new OpCode(0x92, Op.KIL, 1, 0,  AddressingMode.NoneAddressing),
            new OpCode(0x93, Op.AXA, 2, 6,  AddressingMode.IndirectY),
            new OpCode(0x94, Op.STY, 2, 4, AddressingMode.ZeroPageX),
            new OpCode(0x95, Op.STA, 2, 4, AddressingMode.ZeroPageX),
            new OpCode(0x96, Op.STX, 2, 4, AddressingMode.ZeroPageY),
            new OpCode(0x97, Op._SAX, 2, 4,  AddressingMode.ZeroPageY),
            new OpCode(0x98, Op.TYA, 1, 2, AddressingMode.NoneAddressing),
            new OpCode(0x99, Op.STA, 3, 5, AddressingMode.AbsoluteY),
            new OpCode(0x9a, Op.TXS, 1, 2, AddressingMode.NoneAddressing),
            new OpCode(0x9b, Op.XAS, 3, 5,  AddressingMode.AbsoluteY),
            new OpCode(0x9c, Op.SYA, 3, 5,  AddressingMode.AbsoluteX),
            new OpCode(0x9d, Op.STA, 3, 5, AddressingMode.AbsoluteX),
            new OpCode(0x9e, Op.SXA, 3, 5,  AddressingMode.AbsoluteY),
            new OpCode(0x9f, Op.AXA, 3, 5,  AddressingMode.AbsoluteY),
            new OpCode(0xa0, Op.LDY, 2, 2, AddressingMode.Immediate),
            new OpCode(0xa1, Op.LDA, 2, 6, AddressingMode.IndirectX),
            new OpCode(0xa2, Op.LDX, 2, 2, AddressingMode.Immediate),
            new OpCode(0xa3, Op._LAX, 2, 6,  AddressingMode.IndirectX),
            new OpCode(0xa4, Op.LDY, 2, 3, AddressingMode.ZeroPage),
            new OpCode(0xa5, Op.LDA, 2, 3, AddressingMode.ZeroPage),
            new OpCode(0xa6, Op.LDX, 2, 3, AddressingMode.ZeroPage),
            new OpCode(0xa7, Op._LAX, 2, 3,  AddressingMode.ZeroPage),
            new OpCode(0xa8, Op.TAY, 1, 2, AddressingMode.NoneAddressing),
            new OpCode(0xa9, Op.LDA, 2, 2, AddressingMode.Immediate),
            new OpCode(0xaa, Op.TAX, 1, 2, AddressingMode.NoneAddressing),
            new OpCode(0xab, Op.ATX, 2, 2,  AddressingMode.Immediate),
            new OpCode(0xac, Op.LDY, 3, 4, AddressingMode.Absolute),
            new OpCode(0xad, Op.LDA, 3, 4, AddressingMode.Absolute),
            new OpCode(0xae, Op.LDX, 3, 4, AddressingMode.Absolute),
            new OpCode(0xaf, Op._LAX, 3, 4,  AddressingMode.Absolute),
            new OpCode(0xb0, Op.BCS, 2, 2 /*(+1 if branch succeeds +2 if to a new page)*/, AddressingMode.Relative),
            new OpCode(0xb1, Op.LDA, 2, 5 /*+1 if page crossed*/, AddressingMode.IndirectY),
            new OpCode(0xb2, Op.KIL, 1, 0,  AddressingMode.NoneAddressing),
            new OpCode(0xb3, Op._LAX, 2, 5,  AddressingMode.IndirectY),
            new OpCode(0xb4, Op.LDY, 2, 4, AddressingMode.ZeroPageX),
            new OpCode(0xb5, Op.LDA, 2, 4, AddressingMode.ZeroPageX),
            new OpCode(0xb6, Op.LDX, 2, 4, AddressingMode.ZeroPageY),
            new OpCode(0xb7, Op._LAX, 2, 4,  AddressingMode.ZeroPageY),
            new OpCode(0xb8, Op.CLV, 1, 2, AddressingMode.NoneAddressing),
            new OpCode(0xb9, Op.LDA, 3, 4 /*+1 if page crossed*/, AddressingMode.AbsoluteY),
            new OpCode(0xba, Op.TSX, 1, 2, AddressingMode.NoneAddressing),
            new OpCode(0xbb, Op.LAR, 3, 4,  AddressingMode.AbsoluteY),
            new OpCode(0xbc, Op.LDY, 3, 4 /*+1 if page crossed*/, AddressingMode.AbsoluteX),
            new OpCode(0xbd, Op.LDA, 3, 4 /*+1 if page crossed*/, AddressingMode.AbsoluteX),
            new OpCode(0xbe, Op.LDX, 3, 4 /*+1 if page crossed*/, AddressingMode.AbsoluteY),
            new OpCode(0xbf, Op._LAX, 3, 4,  AddressingMode.AbsoluteY),
            new OpCode(0xc0, Op.CPY, 2, 2, AddressingMode.Immediate),
            new OpCode(0xc1, Op.CMP, 2, 6, AddressingMode.IndirectX),
            new OpCode(0xc2, Op._NOP, 2, 2,  AddressingMode.Immediate),
            new OpCode(0xc3, Op._DCP, 2, 8,  AddressingMode.IndirectX),
            new OpCode(0xc4, Op.CPY, 2, 3, AddressingMode.ZeroPage),
            new OpCode(0xc5, Op.CMP, 2, 3, AddressingMode.ZeroPage),
            new OpCode(0xc6, Op.DEC, 2, 5, AddressingMode.ZeroPage),
            new OpCode(0xc7, Op._DCP, 2, 5,  AddressingMode.ZeroPage),
            new OpCode(0xc8, Op.INY, 1, 2, AddressingMode.NoneAddressing),
            new OpCode(0xc9, Op.CMP, 2, 2, AddressingMode.Immediate),
            new OpCode(0xca, Op.DEX, 1, 2, AddressingMode.NoneAddressing),
            new OpCode(0xcb, Op.AXS, 2, 2,  AddressingMode.Immediate),
            new OpCode(0xcc, Op.CPY, 3, 4, AddressingMode.Absolute),
            new OpCode(0xcd, Op.CMP, 3, 4, AddressingMode.Absolute),
            new OpCode(0xce, Op.DEC, 3, 6, AddressingMode.Absolute),
            new OpCode(0xcf, Op._DCP, 3, 6,  AddressingMode.Absolute),
            new OpCode(0xd0, Op.BNE, 2, 2 /*(+1 if branch succeeds +2 if to a new page)*/, AddressingMode.Relative),
            new OpCode(0xd1, Op.CMP, 2, 5 /*+1 if page crossed*/, AddressingMode.IndirectY),
            new OpCode(0xd2, Op.KIL, 1, 0,  AddressingMode.NoneAddressing),
            new OpCode(0xd3, Op._DCP, 2, 8,  AddressingMode.IndirectY),
            new OpCode(0xd4, Op._NOP, 2, 4,  AddressingMode.ZeroPageX),
            new OpCode(0xd5, Op.CMP, 2, 4, AddressingMode.ZeroPageX),
            new OpCode(0xd6, Op.DEC, 2, 6, AddressingMode.ZeroPageX),
            new OpCode(0xd7, Op._DCP, 2, 6,  AddressingMode.ZeroPageX),
            new OpCode(0xD8, Op.CLD, 1, 2, AddressingMode.NoneAddressing),
            new OpCode(0xd9, Op.CMP, 3, 4 /*+1 if page crossed*/, AddressingMode.AbsoluteY),
            new OpCode(0xda, Op._NOP, 1, 2,  AddressingMode.NoneAddressing),
            new OpCode(0xdb, Op._DCP, 3, 7,  AddressingMode.AbsoluteY),
            new OpCode(0xdc, Op._NOP, 3, 4,  AddressingMode.AbsoluteX),
            new OpCode(0xdd, Op.CMP, 3, 4 /*+1 if page crossed*/, AddressingMode.AbsoluteX),
            new OpCode(0xde, Op.DEC, 3, 7, AddressingMode.AbsoluteX),
            new OpCode(0xdf, Op._DCP, 3, 7,  AddressingMode.AbsoluteX),
            new OpCode(0xe0, Op.CPX, 2, 2, AddressingMode.Immediate),
            new OpCode(0xe1, Op.SBC, 2, 6, AddressingMode.IndirectX),
            new OpCode(0xe2, Op._NOP, 2, 2,  AddressingMode.Immediate),
            new OpCode(0xe3, Op._ISB, 2, 8,  AddressingMode.IndirectX),
            new OpCode(0xe4, Op.CPX, 2, 3, AddressingMode.ZeroPage),
            new OpCode(0xe5, Op.SBC, 2, 3, AddressingMode.ZeroPage),
            new OpCode(0xe6, Op.INC, 2, 5, AddressingMode.ZeroPage),
            new OpCode(0xe7, Op._ISB, 2, 5,  AddressingMode.ZeroPage),
            new OpCode(0xe8, Op.INX, 1, 2, AddressingMode.NoneAddressing),
            new OpCode(0xe9, Op.SBC, 2, 2, AddressingMode.Immediate),
            new OpCode(0xea, Op.NOP, 1, 2, AddressingMode.NoneAddressing),
            new OpCode(0xeb, Op._SBC, 2, 2,  AddressingMode.Immediate),
            new OpCode(0xec, Op.CPX, 3, 4, AddressingMode.Absolute),
            new OpCode(0xed, Op.SBC, 3, 4, AddressingMode.Absolute),
            new OpCode(0xee, Op.INC, 3, 6, AddressingMode.Absolute),
            new OpCode(0xef, Op._ISB, 3, 6,  AddressingMode.Absolute),
            new OpCode(0xf0, Op.BEQ, 2, 2 /*(+1 if branch succeeds +2 if to a new page)*/, AddressingMode.Relative),
            new OpCode(0xf1, Op.SBC, 2, 5 /*+1 if page crossed*/, AddressingMode.IndirectY),
            new OpCode(0xf2, Op.KIL, 1, 0,  AddressingMode.NoneAddressing),
            new OpCode(0xf3, Op._ISB, 2, 8,  AddressingMode.IndirectY),
            new OpCode(0xf4, Op._NOP, 2, 4,  AddressingMode.ZeroPageX),
            new OpCode(0xf5, Op.SBC, 2, 4, AddressingMode.ZeroPageX),
            new OpCode(0xf6, Op.INC, 2, 6, AddressingMode.ZeroPageX),
            new OpCode(0xf7, Op._ISB, 2, 6,  AddressingMode.ZeroPageX),
            new OpCode(0xf8, Op.SED, 1, 2, AddressingMode.NoneAddressing),
            new OpCode(0xf9, Op.SBC, 3, 4 /*+1 if page crossed*/, AddressingMode.AbsoluteY),
            new OpCode(0xfa, Op._NOP, 1, 2,  AddressingMode.NoneAddressing),
            new OpCode(0xfb, Op._ISB, 3, 7,  AddressingMode.AbsoluteY),
            new OpCode(0xfc, Op._NOP, 3, 4,  AddressingMode.AbsoluteX),
            new OpCode(0xfd, Op.SBC, 3, 4 /*+1 if page crossed*/, AddressingMode.AbsoluteX),
            new OpCode(0xfe, Op.INC, 3, 7, AddressingMode.AbsoluteX),
            new OpCode(0xff, Op._ISB, 3, 7,  AddressingMode.AbsoluteX),
        };
    }
}
